### ISSUE TITLE
Don't show users tools they can't access

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/opensearch-dashboards-cf-auth-proxy#35]
In order to improve user experience, we want to hide OpenSearch apps users don't have access to.

## Acceptance Criteria
* [ ] GIVEN an app shows up in the menu \
  WHEN I click on it \
  THEN I should not receive a permissions error
* [ ] GIVEN I do not have permissions for an app\
  WHEN I look for it in the menu \
  THEN I should not see it

--- 

## Security considerations
This should not change security, only user experience

## Implementation sketch
* [ ] set the [cluster permissions](https://opensearch.org/docs/latest/security-plugin/access-control/permissions/) appropriately for our roles and each path/plugin 
  * Might be something to be done [via the API](https://opensearch.org/docs/latest/security-plugin/access-control/api/) rather than deployment config
* [ ] Consider what features we can add/support
* We can [use the Security API to write tests](https://opensearch.org/docs/latest/security-plugin/access-control/api/#account)

**Comment by markdboyd** [comment]
Unfortunately, there is no granular system for showing menu links based on user permissions: https://github.com/opensearch-project/security-dashboards-plugin/issues/857.

So this issue is blocked until Opensearch implements some sort of granular permissions system for menu links.

**Comment by JasonTheMain** [comment]
This feature will hopefully be accomplished by https://github.com/cloud-gov/opensearch-boshrelease/issues/180

**Comment by JasonTheMain** [comment]
removed excess plugins view
